version: '3.7'
services:
  app:
    container_name: docker-node-mongo
    restart: always
    build: .
    ports:
      - '3000:3000'
      - '1883:1883'
    links:
      - mongo
    #command: "node ./Mqtt/broker"
    #command: "npm start"   
    volumes:
      - ./:/usr/src/app
    stdin_open: true
    tty: true
    
  mongo:
    restart: always
    container_name: mongo
    image: mongo
    #volumes:
    #  - ./data:/data/db
    ports:
      - '27017:27017'



 