version: '3.7'
services:
  app:
    container_name: docker-node-mongo
    restart: always
    build: .
    ports:
      - '3000:3000'
    links:
      - mongo
    volumes:
      - ./:/usr/src/app
    stdin_open: true
    tty: true 
  mongo:
    container_name: mongo
    image: mongo
    #volumes:
    #  - ./data:/data/db
    ports:
      - '27017:27017'



 